name: Auto Update toki_filter.txt

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 새벽 1시 실행 (원하면 제거 가능)
  workflow_dispatch:      # 수동으로 실행 버튼 제공

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run run.py script
      run: |
        python run.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add toki_filter.txt
        git commit -m "Auto update toki_filter.txt [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
